language: node_js
cache: yarn

script: yarn build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: 'thetalententerprise-upchunk-*.tgz'
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
